name: End-to-End testing

on:
  push: 

jobs:
  push-github:
    name: Push to docker hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Start flyte sandbox
        run: curl -sL https://ctl.flyte.org/install | bash && ./bin/flytectl sandbox start
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Register and execute workflow on flyte cluster
        env:
          FLYTECTL_CONFIG: /home/runner/.flyte/config-sandbox.yaml
        run: pip install flytekit && pyflyte run --remote development/workflow/my_app my_wf
